# hugo server --minify --themesDir ... --baseURL=http://0.0.0.0:1313/example

publishDir: docs

baseURL: https://google-apps-script-snippets.contributor.pw/
theme: hugo-book
disableKinds: ['taxonomy', 'taxonomyTerm']

# Book configuration
disablePathToLower: false
enableGitInfo: true

# Code highlight
# pygmentsStyle: monokailight
pygmentsCodeFences: true
pygmentsStyle: manni

DefaultContentLanguage: en

languages:
  en:
    languageName: English
    title: Google Apps Script snippets
    weight: 1
  ru:
    languageName: Russian
    title: Google Apps Script сниппеты
    weight: 2

params:
  # (Optional, default 6) Set how many table of contents levels to be showed on page.
  # Use false/off to hide ToC, note that 0 will default to 6 (https://gohugo.io/functions/default/)
  # You can also specify this parameter per page in front matter
  BookToC: false

  # (Optional, default none) Set the path to a logo for the book. If the logo is
  # /static/logo.png then the path would be /logo.png
  # BookLogo: /logo.png

  # (Optional, default none) Set leaf bundle to render as side menu
  # When not specified file structure and weights will be used
  BookMenuBundle: /menu

  # (Optional, default docs) Specify section of content to render as menu
  # You can also set value to '*' to render all sections to menu
  BookSection: '*'

  # (Optional) This value is duplicate of $link-color for making active link highlight in menu bundle mode
  # BookMenuBundleActiveLinkColor: "\#004ed0"

  # Set source repository location.
  # Used for 'Last Modified' and 'Edit this page' links.
  BookRepo: https://github.com/contributorpw/google-apps-script-snippets

  # Enable "Edit this page" links for 'doc' page type.
  # Disabled by default. Uncomment to enable. Requires 'BookRepo' param.
  # Path must point to 'content' directory of repo.
  BookEditPath: edit/master

  # Configure the date format used on the pages
  # - In git information
  # - In blog posts
  BookDateFormat: 'Jan 2, 2006'

  # (Optional, default true) Enables search function with lunr.js,
  # Index is built on fly, therefore it might slowdown your website.
  BookSearch: true
